### ISSUE TITLE
Python 3.6 is not supported but is included in `python_requires`

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/func_adl#101]
Use of <https://github.com/iris-hep/func_adl/blob/b6416eaa9b23d5091c8cbdf0693f6d5f7e382bde/func_adl/object_stream.py#L1> means that Python 3.6 is not supported, since [`annotations` was added to `__future__` in 3.7](https://docs.python.org/3/library/__future__.html), yet `setup.py` claims that 3.6 is supported: <https://github.com/iris-hep/func_adl/blob/b6416eaa9b23d5091c8cbdf0693f6d5f7e382bde/setup.py#L73>

**Comment by gordonwatts** [comment]
Need to drop support for 3.6 in the setup files!
