### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/func_adl#104]
Python 3.11 was released [today](https://www.python.org/downloads/release/python-3110/). Once `func_adl` supports it, downstream packages can follow (like `func_adl_uproot`). From a quick glance, it doesn't look like 3.11 brings any Python AST changes.

**Comment by gordonwatts** [comment]
It is a little disapointing - it adds all this source code tracking stuff, but I don't think the `inspect.getsource` is improved!
