### ISSUE TITLE
no default URL scheme

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/func_adl#25]
When I started testing this package, I expected something like `EventDataset('ntuple.root')` to work, but it will give an error:

```python
>>> import func_adl
>>> func_adl.EventDataset('ntuple.root')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mproffit/iris/code/func_adl/func_adl/EventDataset.py", line 91, in __init__
    self.url = [_fixup_url(u, _parse_and_check_dataset_url(u)) for u in l_url]
  File "/home/mproffit/iris/code/func_adl/func_adl/EventDataset.py", line 91, in <listcomp>
    self.url = [_fixup_url(u, _parse_and_check_dataset_url(u)) for u in l_url]
  File "/home/mproffit/iris/code/func_adl/func_adl/EventDataset.py", line 59, in _parse_and_check_dataset_url
    raise EventDatasetURLException(f'EventDataSet({u}) has no scheme (file://, localds://, etc.)')
func_adl.EventDataset.EventDatasetURLException: EventDataSet(ntuple.root) has no scheme (file://, localds://, etc.)
```

 It would be nice if `file` was the default scheme for the string passed to `EventDataset()` so that you didn't have to type `file://` before a local path.

(As a side note, I'm curious what `localds` means and how it would be different from `file`...)

**Comment by gordonwatts** [comment]
`localds` means download a file from a dataset locally. If you are using `func_adl` that won't work right, you need the xAOD version for now.

The general scheme: Every dataset has a scheme. The scheme tells the system how to get its hand on the file. I think there is also `gridds`... This got left behind a little bit while working on ServiceX. That stands to change how we think about datasets. And you are right, we need to make it coherrent.

As far as a default schema... the problem I had with that is you get into all sorts of detection logic. Which I hated. So I just left everything where you had to actually put the schema in there. THis was under the ruberic of not taking too many "magic" actions behind the users back.

**Comment by gordonwatts** [comment]
So this issue no longer makes sense - Now you would create a local file xaod or local file uproot and that would run locally and expect local path names.

**Comment by masonproffitt** [comment]
> So this issue no longer makes sense - Now you would create a local file xaod or local file uproot and that would run locally and expect local path names.

Just to try to translate this: what you're saying here is that there needs to be a subclass of `EventDataset` in func_adl_uproot that correctly handles the given path, right?

**Comment by gordonwatts** [comment]
Right - we currently have ServiceXDatasetSource that handles sending the query to ServiceX. You would need a UprootDatasetSource, which would take file paths, to run locally (or LocalUprootDatasetSource or whatever you want to call the object). Then you can run everything locally.

On my list is to do something similar for xAOD - "xAODDatasetSource" which you can give a single xAOD file and it will run on it. And then I want to make some sort of multi-thing which can run many of any type in parallel, even locally, but is very stupid about it. Something like `ParallelDatasetSource(x1, x2, x3, x4)` where x1, x2, x3, x4 are all derived from EventData's and can then be invoked async and run in parallel through the virtues of async on python, locally. If you want to tackle any of these things, I would say go for it!
