### ISSUE TITLE
_extract_dataset_info() returns a string, not an EventDataset

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/func_adl#64]
There's something wrong here:

https://github.com/iris-hep/func_adl/blob/6576cbe771b7b7765ca70f4727c2d3f0bebb5f58/func_adl/event_dataset.py#L79-L86

`ast.literal_eval()` cannot return anything other than Python literals (strings, numbers, etc.). Yet https://github.com/iris-hep/func_adl/blob/6576cbe771b7b7765ca70f4727c2d3f0bebb5f58/func_adl/object_stream.py#L212-L214 via https://github.com/iris-hep/func_adl/blob/6576cbe771b7b7765ca70f4727c2d3f0bebb5f58/func_adl/event_dataset.py#L89-L94 clearly depends on `_extract_dataset_info()` returning an object with an `execute_result_async` attribute.

I ran into this issue while looking into https://github.com/iris-hep/func_adl_uproot/issues/22. I don't actually understand how this currently works when running with ServiceX--I'm guessing there must be an override somewhere in the ServiceX-related classes? That's what I'm having to resort to, but it would be nice to get this fixed here.

**Comment by gordonwatts** [comment]
That definitely looks like a bug - at the very least, a type-decl bug.

**Comment by masonproffitt** [comment]
Ah this is the line:

https://github.com/iris-hep/func_adl/blob/6576cbe771b7b7765ca70f4727c2d3f0bebb5f58/func_adl/event_dataset.py#L23

`Constant` doesn't seem like the right way to carry this around

**Comment by masonproffitt** [comment]
Yeah, this is a significant problem for the Uproot backend because it expects the first argument of `EventDataset` in the AST to be the data file(s). Can we move the `self` value into a property that's not used by the standard Python AST `Call` (that is, basically anything other than `args`)? So we could do something like:

```python
temp_ast = (function_call('EventDataset', args)`

**Comment by masonproffitt** [comment]
In fact, you don't even have to carry around the object; you only need the class. That's what motivated me to try this: <https://github.com/iris-hep/func_adl_uproot/blob/d497c710bf628847d0cea0324fe2e7088768f3e1/func_adl_uproot/dataset.py#L13>. And now that I think of it, we probably actually only need a reference to the right `execute_result_async()` rather than the entire class. Trying to carry around all of the information is also leading to an unfortunate circular dependency of `ObjectStream` on `event_dataset.py` (see <https://github.com/iris-hep/func_adl/blob/6576cbe771b7b7765ca70f4727c2d3f0bebb5f58/func_adl/object_stream.py#L211>).

Ultimately, I think we really just need to agree on a place to put some kind of reference that leads to the correct executor. I'd be fine with any method that doesn't modify the standard Python AST fields.
